name: CloudPub Client (Canary)
slug: cloudpub-canary
version: 3.0.0-1
description: Тестовая версия дополнения
url: https://github.com/black-roland/hassio-addon-cloudpub
init: false
startup: application
boot: auto
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
advanced: false
stage: experimental
map:
  - type: addon_config
    read_only: false
options:
  token: ""
  clo_log_level: warn
  services:
    - type: http
      local_addr: homeassistant:8123
      name: homeassistant
schema:
  token: str
  services:
    - type: list(http|https|tcp|udp|rtsp|1c)
      local_addr: str
      name: str?
  clo_log_level: list(debug|info|warn|error)
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
